### ISSUE TITLE
Constants.platform.ios.model has been deprecated

### ISSUE THREAD

**Issue by stevekuznetsov** [stevekuznetsov/avalanche-forecast#21]
Seeing this warning on startup:

```
Constants.platform.ios.model has been deprecated in favor of expo-device's Device.modelName property. This API will be removed in SDK 45.
at node_modules/expo-constants/build/Constants.js:145:28 in Object.defineProperty$argument_2.get
at node_modules/expo-asset/node_modules/expo-constants/build/Constants.js:141:54 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo-asset/build/PlatformUtils.js:2:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo-asset/build/AssetSources.js:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo-asset/build/Asset.js:3:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo-asset/build/Asset.fx.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo-asset/build/index.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo/build/Expo.fx.js:6:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo/build/launch/registerRootComponent.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/expo/AppEntry.js:1:0 in <global>
at node_modules/metro-runtime/src/polyfills/require.js:339:11 in loadModuleImplementation
at node_modules/metro-runtime/src/polyfills/require.js:200:44 in guardedLoadModule
at http://192.168.86.23:19000/node_modules/expo/AppEntry.bundle?platform=ios&dev=true&hot=false&strict=false&minify=false:null in global code
```

`expo doctor` finds no issues with our dependencies, unclear what is causing this

**Comment by floatplane** [comment]
this got fixed when we updated Expo/RN
